export const STORAGE_KEY_SETTINGS = 'DDP_CryptoMinerPulseSettings_1';
export const STORAGE_KEY_DATA = 'DDP_CryptoMinerPulseData_1';
export const STORAGE_KEY_EXPORT = 'DDP_CryptoMinerPulseExport_1';
export const STORAGE_KEY_LANGUAGE = 'DDP_CryptoMinerPulseLang_1';

export const MAX_DATA_POINTS = 60;
export const SHARES_UPDATE_INTERVAL = 3 * 60 * 1000;

export const DEFAULT_LANG = 'pt-BR';

export const translations = {
    'pt-BR': {
        settingsTitle: 'Configurações',
        apiUrlLabel: 'API URL',
        refreshIntervalLabel: 'Intervalo de atualização (ms)',
        clearHistory: 'Limpar Histórico',
        save: 'Salvar',
        tagline: 'O dashboard do seu garimpo digital.',
        statusConnecting: 'A conectar...',
        statusOnline: 'Online',
        statusOffline: 'Offline',
        exportCsv: 'Exportar CSV',
        languageToggle: 'EN',
        hashrate10sCard: 'Hashrate (10s)',
        hashrate10sTooltip: 'Velocidade atual. Indica quantos cálculos seu PC faz por segundo. Quanto maior, melhor.',
        sharesAccepted: 'Shares Aceitos',
        sharesAcceptedTooltip: 'Trabalhos válidos entregues. São eles que confirmam seu esforço e geram sua recompensa.',
        sharesRejected: 'Rejeitados',
        sharesRejectedTooltip: 'Trabalhos inválidos. Geralmente causados por internet ruim ou configuração errada. Desperdício de energia.',
        avgShareTime: 'Tempo Médio Share',
        avgShareTimeTooltip: 'Tempo médio para seu PC encontrar uma solução. Máquinas mais rápidas têm tempos menores.',
        uptimeLabel: 'Uptime',
        uptimeTooltip: 'Tempo total que o minerador está rodando sem desligar ou travar.',
        hashrateEvolution: 'Evolução do Hashrate',
        sharesDistribution: 'Distribuição de Shares',
        totalLabel: 'Total',
        diffLabel: 'Diff',
        diffTooltip: 'Dificuldade. Define o quão difícil é resolver o problema matemático atual.',
        sharesEvolution: 'Evolução dos Shares',
        miningStation: 'Estação de Mineração',
        workerIdLabel: 'Worker ID',
        workerIdTooltip: 'Nome que identifica esta máquina na sua conta ou na Pool de mineração.',
        cpuLabel: 'CPU',
        cpuTooltip: 'Modelo do processador que está realizando o trabalho de mineração.',
        algoLabel: 'Algoritmo',
        algoTooltip: 'A fórmula matemática específica usada para minerar esta moeda (ex: rx/0 para Monero).',
        poolLabel: 'Pool',
        poolTooltip: 'Servidor coletivo onde vários mineradores se unem para aumentar a frequência de ganhos.',
        pingLabel: 'Ping',
        pingTooltip: 'Latência da conexão. Tempo de resposta entre você e a Pool. Quanto menor, melhor.',
        hugePagesLabel: 'Huge Pages',
        hugePagesTooltip: 'Otimização de memória avançada. Se estiver 100%, sua velocidade de mineração aumenta muito.',
        footerBy: 'Desenvolvido por',
        exportEmptyAlert: 'Nenhuma leitura disponível para exportar.',
        notAvailable: 'Não disponível',
        hashrate10sDataset: 'Hashrate (10s)',
        hashrate60sDataset: 'Hashrate (60s)',
        hashrate15mDataset: 'Hashrate (15m)',
        sharesAcceptedDataset: 'Aceitos',
        sharesTotalDataset: 'Totais'
    },
    'en-US': {
        settingsTitle: 'Settings',
        apiUrlLabel: 'API URL',
        refreshIntervalLabel: 'Refresh interval (ms)',
        clearHistory: 'Clear History',
        save: 'Save',
        tagline: 'Your digital mining dashboard.',
        statusConnecting: 'Connecting...',
        statusOnline: 'Online',
        statusOffline: 'Offline',
        exportCsv: 'Export CSV',
        languageToggle: 'PT',
        hashrate10sCard: 'Hashrate (10s)',
        hashrate10sTooltip: 'Current speed. Shows how many calculations your PC does per second. Higher is better.',
        sharesAccepted: 'Accepted Shares',
        sharesAcceptedTooltip: 'Valid jobs delivered. They confirm your effort and generate your reward.',
        sharesRejected: 'Rejected',
        sharesRejectedTooltip: 'Invalid jobs. Usually caused by poor internet or wrong settings. Wasted energy.',
        avgShareTime: 'Avg Share Time',
        avgShareTimeTooltip: 'Average time for your PC to find a solution. Faster machines have lower times.',
        uptimeLabel: 'Uptime',
        uptimeTooltip: 'Total time the miner has been running without stopping or crashing.',
        hashrateEvolution: 'Hashrate Evolution',
        sharesDistribution: 'Share Distribution',
        totalLabel: 'Total',
        diffLabel: 'Diff',
        diffTooltip: 'Difficulty. Defines how hard it is to solve the current math problem.',
        sharesEvolution: 'Shares Evolution',
        miningStation: 'Mining Station',
        workerIdLabel: 'Worker ID',
        workerIdTooltip: 'Name that identifies this machine in your account or mining pool.',
        cpuLabel: 'CPU',
        cpuTooltip: 'Processor model that is performing the mining work.',
        algoLabel: 'Algorithm',
        algoTooltip: 'Specific math formula used to mine this coin (e.g., rx/0 for Monero).',
        poolLabel: 'Pool',
        poolTooltip: 'Collective server where multiple miners join to increase payout frequency.',
        pingLabel: 'Ping',
        pingTooltip: 'Connection latency. Response time between you and the pool. Lower is better.',
        hugePagesLabel: 'Huge Pages',
        hugePagesTooltip: 'Advanced memory optimization. If it is 100%, your mining speed increases a lot.',
        footerBy: 'Built by',
        exportEmptyAlert: 'No readings available to export.',
        notAvailable: 'Not available',
        hashrate10sDataset: 'Hashrate (10s)',
        hashrate60sDataset: 'Hashrate (60s)',
        hashrate15mDataset: 'Hashrate (15m)',
        sharesAcceptedDataset: 'Accepted',
        sharesTotalDataset: 'Total'
    }
};

export const PARTICLE_COLOR = 'rgba(16, 185, 129, 0.55)';
